# Generated by Django 4.0.6 on 2022-07-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('lang_fa', models.CharField(max_length=400, null=True)),
                ('lang_en', models.CharField(max_length=400, null=True)),
                ('hatag', models.CharField(max_length=200, null=True)),
                ('priority', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TweetsLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=200)),
                ('label_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('created_at', models.DateField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('profile_image_url', models.CharField(max_length=200, null=True)),
                ('protected', models.BooleanField(null=True)),
                ('public_metrics', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('verified', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersTweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets_id', models.CharField(max_length=200)),
                ('users_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userstweets',
            constraint=models.UniqueConstraint(fields=('tweets_id', 'users_id'), name='unique_migration_UserTweets_combination'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(fields=('user_name', 'user_id'), name='unique_migration_User_combination'),
        ),
        migrations.AddConstraint(
            model_name='tweetslabels',
            constraint=models.UniqueConstraint(fields=('tweet_id', 'label_id'), name='unique_migration_Tweetslabels_combination'),
        ),
        migrations.AddConstraint(
            model_name='labels',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_migration_labels_combination'),
        ),
    ]
