# Generated by Django 4.1.1 on 2022-12-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet_id', models.CharField(max_length=200)),
                ('reported_by', models.CharField(max_length=200)),
                ('is_archived', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tweetslabels',
            name='label_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tweetslabels',
            name='tweet_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
