# Generated by Django 4.1.1 on 2023-01-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_usersinfo_tweets_archive_tweets_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AddField(
            model_name='tweets',
            name='archive',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='conversation_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='created_at',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='deleted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='in_reply_to_user_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='lang',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='like_count',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='possibly_sensitive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='public_metrics',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='quote_count',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='referenced_tweets',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='reply_count',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='reply_settings',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='retweet_count',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='source',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tweets',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
