# Generated by Django 4.1.1 on 2023-01-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_tweets_archive_tweets_conversation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersinfo',
            name='status',
        ),
    ]
