# Generated by Django 4.1.1 on 2023-01-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_usersinfo_status_tweets_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='contributors_enabled',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='created_at',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='favourites_count',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='followers_count',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='friends_count',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='geo_enabled',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='lang',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='listed_count',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='profile_image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='protected',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='screen_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='statuses_count',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='time_zone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='user_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='utc_offset',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='verified',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
